[package]
name = "postino-workspace"
version.workspace = true
edition.workspace = true
publish.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
postino-core = { path = "../postino-core" }
postino-format = { path = "../postino-format" }
thiserror = { workspace = true }
tempfile = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }

[lints]
workspace = true
